-- ForeverDB initial backend schema
-- Prepared for Supabase/PostgreSQL; not yet applied to the project.

create table if not exists public.mobs (
    id bigint generated by default as identity primary key,
    npc_id bigint not null unique,
    name text,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

create table if not exists public.items (
    id bigint generated by default as identity primary key,
    item_id bigint not null unique,
    name text,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

create table if not exists public.installations (
    id uuid primary key,
    first_seen_at timestamptz not null default now(),
    last_seen_at timestamptz not null default now()
);

create table if not exists public.upload_batches (
    id uuid primary key,
    installation_id uuid not null references public.installations(id),
    schema_version integer not null,
    addon_version text not null,
    received_at timestamptz not null default now()
);

create table if not exists public.mob_loot_stats (
    mob_id bigint not null references public.mobs(id) on delete cascade,
    item_id bigint not null references public.items(id) on delete cascade,
    observations bigint not null default 0 check (observations >= 0),
    drop_count bigint not null default 0 check (drop_count >= 0),
    quantity bigint not null default 0 check (quantity >= 0),
    updated_at timestamptz not null default now(),
    primary key (mob_id, item_id)
);

create table if not exists public.mob_skinning_stats (
    mob_id bigint not null references public.mobs(id) on delete cascade,
    item_id bigint not null references public.items(id) on delete cascade,
    observations bigint not null default 0 check (observations >= 0),
    drop_count bigint not null default 0 check (drop_count >= 0),
    quantity bigint not null default 0 check (quantity >= 0),
    updated_at timestamptz not null default now(),
    primary key (mob_id, item_id)
);

create index if not exists mobs_name_idx on public.mobs using btree (lower(name));
create index if not exists items_name_idx on public.items using btree (lower(name));
